CREATE DATABASE IF NOT EXISTS mastergame;
USE mastergame;

CREATE TABLE IF NOT EXISTS usuarios(
	id INT(10) PRIMARY KEY AUTO_INCREMENT NOT NULL,
    nombre VARCHAR(30) NOT NULL,
    apellido VARCHAR(30) NOT NULL,
    mail VARCHAR(50) NOT NULL,
    usuario VARCHAR(30) NOT NULL,
    clave VARCHAR(600) NOT NULL,
    tipo_usuario VARCHAR(8) NOT NULL
);

CREATE TABLE IF NOT EXISTS grupos_usuarios(
	id INT(10) PRIMARY KEY AUTO_INCREMENT NOT NULL,
    nombre VARCHAR(30) NOT NULL
);
